[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  # With ssr:false, Nitro generated public is "dist" (per build logs)
  publish = "dist"

# Optional: cache pnpm store between builds
[build.environment]
  NPM_FLAGS = "--version" # Prevent Netlify from running npm install
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-lighthouse"


