[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  # Nitro Netlify preset outputs to .netlify/publish
  publish = ".netlify/publish"

# Optional: cache pnpm store between builds
[build.environment]
  NPM_FLAGS = "--version" # Prevent Netlify from running npm install
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-lighthouse"


